feat: handling for canvas deletion
Excali-Studio/excali-api pull request #30
Opened 2024-11-25 13:39 UTC by matevszm

2024-11-25 14:46 UTC, coredumped7893 requested changes

2024-11-25 14:46 UTC, coredumped7893 commented on src/canvas/canvas.controller.ts
> +    return await this.canvasService.deleteCanvasById(uuid);
What happens when we want to delete non-existing canvas? Does it throw 403?

2024-11-25 14:46 UTC, coredumped7893 commented on src/canvas/entity/canvas-state.entity.ts
> +  @ManyToOne(() => CanvasEntity, { nullable: false, onDelete: 'CASCADE' })
imo. It's risky to make any cascading deletions on the db. We should handle this in a 'soft' delete way.

2024-11-25 14:46 UTC, coredumped7893 commented on src/canvas/entity/canvas-access.entity.ts
> +  @ManyToOne(() => CanvasEntity, { nullable: false, onDelete: 'CASCADE' })
imo. It's risky to make any cascading deletions on the db. We should handle this in a 'soft' delete way.

2024-11-25 14:46 UTC, coredumped7893 commented on src/canvas/entity/canvas-state.entity.ts
> +  @ManyToOne(() => CanvasEntity, { nullable: false, onDelete: 'CASCADE' })
I would add flag `deleted: boolean;` where "Delete" action just sets this flag to true.
In addition to that, all read methods should return only records where `deleted = false`.
This way you dont have to make any irreversible deletions on the db and it would be possible to "restore" some canvas in case of accidental deletion ;)

2024-11-26 09:17 UTC, matevszm commented on src/canvas/canvas.controller.ts
> +    return await this.canvasService.deleteCanvasById(uuid);
Probably with this code server will throw 500, now I cover that case.

2024-11-26 09:17 UTC, matevszm commented on src/canvas/entity/canvas-state.entity.ts
> +  @ManyToOne(() => CanvasEntity, { nullable: false, onDelete: 'CASCADE' })
done.

2024-11-26 09:18 UTC, matevszm commented on src/canvas/entity/canvas-access.entity.ts
> +  @ManyToOne(() => CanvasEntity, { nullable: false, onDelete: 'CASCADE' })
done.

2024-11-26 11:18 UTC, coredumped7893 requested changes

2024-11-26 11:18 UTC, coredumped7893 commented on src/canvas/canvas.service.ts
> +    if (canvas.deleted) throw new NotFoundException();
maybe lets just move this condition to the query inside the where block

2024-11-26 11:18 UTC, coredumped7893 commented on src/canvas/entity/canvas.entity.ts
> +  @Column({ type: 'boolean', default: false })
add nullable: false

2024-11-26 13:19 UTC, merged